---
    version: 2.1 
    
    jobs:
      my_1st_step:
        docker:
          - image: circleci/python:3.6
        steps:
          - checkout
          - run: echo "A minimal CircleCI pipleline step 1"
          - run: touch venv/step1.txt
          - persist_to_workspace:
            root: /home/circleci
            paths:
              - project

        
      my_2nd_step:
        docker:
          - image: circleci/python:3.6
        steps:
          - checkout
          - attach_workspace:
                at: /home/circleci
          - run: echo "A minimal CircleCI pipleline step2"
          - run: ls venv
        
    
    
    workflows:
      version: 2.1
      myWorkflow:
        jobs:
          - my_1st_step
          - my_2nd_step:
              requires:
                - my_1st_step