---
    version: 2.1
    orbs:
      node: circleci/node@2.1.1

    jobs:
      my_1st_step:
        docker:
          - image: circleci/python:3.6
        steps:
          - checkout
          - node/install:
                node-version: latest
          - run: echo "A minimal CircleCI pipleline step 1"
          - run: node --version
        
      my_2nd_step:
        docker:
          - image: circleci/python:3.6
        steps:
          - checkout
          - run: echo "A minimal CircleCI pipleline step2"
          - run: npm --version
        
    workflows:
      version: 2.1
      myWorkflow:
        jobs:
          - my_1st_step
          - my_2nd_step:
              requires:
                - my_1st_step