---
    version: 2.1 
    
    jobs:
      my_1st_step:
        docker:
          - image: circleci/python:3.6
        steps:
          - checkout
          - run: echo "A minimal CircleCI pipleline step 1"
          - run: touch step1.txt
          - save_cache:
                key: dependency-cache-{{ checksum "requirements.txt" }}
                paths:
                    - .
        
      my_2nd_step:
        docker:
          - image: circleci/python:3.6
        steps:
          - checkout
          - restore_cache:
                key: dependency-cache-{{ checksum "requirements.txt" }}
          - run: echo "A minimal CircleCI pipleline step2"
          - run: ls
        
    
    
    workflows:
      version: 2.1
      myWorkflow:
        jobs:
          - my_1st_step
          - my_2nd_step:
              requires:
                - my_1st_step